defaults:
  - preprocess: default
  - dataset: default
  - model: base
  - train: default
name: base-transformer-bs64-600k-100hz-tome50hzPLEBatchTopk-vq16384-2stage-ropebase10kposids-window128-lneps1e2-nodropout-sampleprob1
log_dir: pl_log
debug: false
resume_ckpt: null
wandb_id: null
ckpt: '/home/hoyso/projects/AudioTokenization/DTMAE/outputs/2025-11-23/22-32-07/pl_log/last.ckpt' # infer
input_dir: null # infer
output_dir: null # infer
hydra:
  output_subdir: hydra
  job:
    chdir: True