defaults:
  - preprocess: default
  - dataset: default
  - model: base
  - train: default
name: base-sqeezeformer-bs64-600k-vq16384-100hz-tome50hzToMeK2Newiter4-2stage-causal
log_dir: pl_log
debug: false
resume_ckpt: null
wandb_id: null
ckpt: null # infer
input_dir: null # infer
output_dir: null # infer
hydra:
  output_subdir: hydra
  job:
    chdir: True