codec_encoder:
  hop_length: 160 #256
  n_fft: 640 #1024
  window_size: 640 #1024
  dim: 512
  n_layers_level1: 6
  n_layers_level2: 12
  r: 0.5
  n_head: 4
  ffn_mult: 4
  dropout: 0
  max_position_embeddings: 8192
  base: 10000
  causal: False
  out_channels: 512
  norm_eps: 1e-2
  attn_window_size: [64, 64]

codec_decoder:
  in_channels: 512
  hop_length: 160 #256
  n_fft: 640 #1024
  window_size: 640 #1024
  dim: 512
  n_layers_level1: 6
  n_layers_level2: 12
  r: 0.5
  n_head: 4
  ffn_mult: 4
  dropout: 0
  max_position_embeddings: 8192
  base: 10000
  causal: False
  vq_num_quantizers: 1 # 8
  vq_commit_weight: 0.5
  vq_weight_init: False
  fsq: False
  fsq_levels: [8,8,8,5,5,5]
  vq_full_commit_loss: False
  codebook_size: 16384 # 1024
  codebook_dim: 8
  norm_eps: 1e-2
  attn_window_size: [64, 64]

resampler:
  use_dtp: True
  dtp_cls: PLEBatchTopK
  dtp_params:
    r: 0.5
    initial_tau: 1.0
    ema_mu: 0.95
    eta0: 0.1
    decay_T: 1000.0
    tau_min: 1e-6
    tau_max: 1e6
    update_every: 1
    max_s: null
    sample_prob: 0
    min_mask_span: 1
    max_mask_span: 1
    min_mask_prob: 0.5
    max_mask_prob: 0.5
  downsampler_cls: FrontierDownsampler
  downsampler_params: {}
  upsampler_cls: MaskUpsampler
  upsampler_params:
    dim: 512

mpd:
  periods: [2, 3, 5, 7, 11]
  max_downsample_channels: 256
  channels: 8
  channel_increasing_factor: 4
  use_weight_norm: False

mstft:
  stft_params:
    fft_sizes: [78, 126, 206, 334, 542, 876, 1418, 2296]
    hop_sizes: [39, 63, 103, 167, 271, 438, 709, 1148]
    win_lengths: [78, 126, 206, 334, 542, 876, 1418, 2296]
    window: hann_window
  in_channels: 1
  out_channels: 1
  kernel_sizes: [5, 3]
  channels: 8
  max_downsample_channels: 256
  downsample_scales: [2, 2, 2]
  use_weight_norm: False
