defaults:
  - preprocess: default
  - dataset: default
  - model: base
  - train: default
name: base-transformer-bs64-600k-vq16384-100hz-tome50hzPLETopKrandom-noargmax-2stage
log_dir: pl_log
debug: false
resume_ckpt: '/home/hoyso/projects/AudioTokenization/BigCodec_SSL/results0930/transformer-PLETopK_ong/10-58-16/pl_log/last.ckpt'
wandb_id: 'o8u8ae7g'
ckpt: null # infer
input_dir: null # infer
output_dir: null # infer
hydra:
  output_subdir: hydra
  job:
    chdir: True