defaults:
  - preprocess: default
  - dataset: default
  - model: base
  - train: default
name: base-transformer-bs64-600k-vq65536-100hz-conv50hz-2stage-convstride2
log_dir: pl_log
debug: false
resume_ckpt: '//home/hoyso/projects/AudioTokenization/BigCodec_SSL/outputs/2025-09-29/16-59-16/pl_log/last.ckpt'
wandb_id: 'mfvjh6cw'
ckpt: null # infer
input_dir: null # infer
output_dir: null # infer
hydra:
  output_subdir: hydra
  job:
    chdir: True