codec_encoder:
  type: 'conformer_stft'
  # out_channels: 512
  # ngf: 32
  # use_rnn: True
  # rnn_bidirectional: False
  # rnn_num_layers: 2
  # up_ratios: [4, 4, 4, 5]
  # dilations: [1, 3, 9]
  # causal: False
  # antialias: False
  hop_length: 200 #256
  n_fft: 800 #1024
  window_size: 800 #1024
  dim: 256
  n_layers: 6
  n_head: 8
  ffn_mult: 4
  conv_kernel_size: 31
  dropout: 0.1
  max_seq_len: 8192
  rope_theta: 500
  causal: False
  out_channels: 256

codec_decoder:
  type: 'conformer_istft'
  # in_channels: 512
  # upsample_initial_channel: 512
  # ngf: 32
  # use_rnn: True
  # rnn_bidirectional: False
  # rnn_num_layers: 2
  # up_ratios: [5, 4, 4, 4] # [2, 5, 5, 4]
  # dilations: [1, 3, 9]
  # causal: False
  # antialias: False
  in_channels: 256
  hop_length: 200 #256
  n_fft: 800 #1024
  window_size: 800 #1024
  dim: 256
  n_layers: 6
  n_head: 8
  ffn_mult: 4
  conv_kernel_size: 31
  dropout: 0.1
  max_seq_len: 8192
  rope_theta: 500
  causal: False
  vq_num_quantizers: 1 # 8
  vq_commit_weight: 0.25
  vq_weight_init: False
  fsq: False
  fsq_levels: [4,4,4,4,4,8]
  vq_full_commit_loss: False
  codebook_size: 8192 # 1024
  codebook_dim: 8

mpd:
  periods: [2, 3, 5, 7, 11]
  max_downsample_channels: 512
  channels: 16
  channel_increasing_factor: 4

mstft:
  stft_params:
    fft_sizes: [128, 256, 512, 1024, 2048]
    hop_sizes: [32, 64, 128, 256, 512]
    win_lengths: [128, 256, 512, 1024, 2048]
    window: hann_window
  in_channels: 1
  out_channels: 1
  kernel_sizes: [5, 3]
  channels: 32
  max_downsample_channels: 512
  downsample_scales: [2, 2, 2]
  use_weight_norm: True
