defaults:
  - preprocess: default
  - dataset: default
  - model: base
  - train: default
name: base-transformer-bs64-600k-100hz-tome50hzPLEBatchTopk-sampleprob1-vq16384-2stage-ropebase10kposids-window128-lneps1e2-layerscale1-qknorm-nodropout
log_dir: pl_log
debug: false
resume_ckpt: null
wandb_id: null
ckpt: '/home/hoyso/projects/AudioTokenization/DTMAE/outputs/2025-11-30/22-44-27/pl_log/last.ckpt' # infer
input_dir: null # infer
output_dir: null # infer
hydra:
  output_subdir: hydra
  job:
    chdir: True