defaults:
  - preprocess: default
  - dataset: mls_eng_streaming
  - model: base
  - train: default
name: base-mls-transformer-bs64-600k-100hz-tome50hzPLEBatchTopk-ms4-lengthembed3-vq16384-2stage-ropebase10kposids-window128-lneps1e2-layerscale1-qknorm-nodropout
log_dir: pl_log
debug: false
resume_ckpt: null
wandb_id: null
ckpt: null # infer
input_dir: null # infer
output_dir: null # infer
hydra:
  output_subdir: hydra
  job:
    chdir: True