defaults:
  - preprocess: default
  - dataset: default
  - model: base
  - train: default
name: onformer-stft-istft-1024-ls-600k-vq16384-100hz-topktome50hzk4-maskingupsampler
log_dir: pl_log
debug: false
resume_ckpt: '/home/hoyso/projects/AudioTokenization/BigCodec_SSL/outputs/2025-08-09/09-04-10/pl_log/last.ckpt'
wandb_id: 'r44v70ox'
ckpt: null # infer
input_dir: null # infer
output_dir: null # infer
hydra:
  output_subdir: hydra
  job:
    chdir: True