defaults:
  - preprocess: default
  - dataset: default
  - model: base
  - train: default
name: base-transformer-bs64-600k-100hz-tome50hzPLEBatchTopK-TAAEDitheredFSQ555555noisedropout0-2stage-ropebase10kposids-window128-lneps1e2-layerscale1-qknorm-nodropout
log_dir: pl_log
debug: false
resume_ckpt: '/home/hoyso/projects/AudioTokenization/results/results0211/17-02-24/pl_log/last.ckpt'
wandb_id: 'pprymrsr'
ckpt: null # infer
input_dir: null # infer
output_dir: null # infer
hydra:
  output_subdir: hydra
  job:
    chdir: True