defaults:
  - preprocess: default
  - dataset: default
  - model: base
  - train: default
name: conformer-stft-istft-512-ls-300k-vq8192-80hz-no-final-norm-no-scale
log_dir: pl_log
debug: false
resume_ckpt: null
wandb_id: null
ckpt: null # infer
input_dir: null # infer
output_dir: null # infer
hydra:
  output_subdir: hydra
  job:
    chdir: True